### ISSUE TITLE
exception when calling widgetsApi.getWidgetformData

### ISSUE THREAD

**Issue by yenhsiac** [adobe-sign/AdobeSignJsSdk#4]
Users/cchang/projects/adobesign-widget-manager/node_modules/adobe-sign-sdk/rest-api-sdk/src/utils/ApiClient.js:536
return data.map(function(item) {
^
TypeError: data.map is not a function
at Function.ApiClient.convertToType (/Users/cchang/projects/adobesign-widget-manager/node_modules/adobe-sign-sdk/rest-api-sdk/src/utils/ApiClient.js:536:23)
at Function.WidgetAgreements.constructFromObject (/Users/cchang/projects/adobesign-widget-manager/node_modules/adobe-sign-sdk/rest-api-sdk/src/model/widgets/WidgetAgreements.js:72:44)
at Function.ApiClient.convertToType (/Users/cchang/projects/adobesign-widget-manager/node_modules/adobe-sign-sdk/rest-api-sdk/src/utils/ApiClient.js:532:23)
at deserialize (/Users/cchang/projects/adobesign-widget-manager/node_modules/adobe-sign-sdk/rest-api-sdk/src/utils/ApiClient.js:295:23)
at /Users/cchang/projects/adobesign-widget-manager/node_modules/adobe-sign-sdk/rest-api-sdk/src/utils/ApiClient.js:452:28
at Request.callback (/Users/cchang/projects/adobesign-widget-manager/node_modules/superagent/lib/node/index.js:617:12)
at /Users/cchang/projects/adobesign-widget-manager/node_modules/superagent/lib/node/index.js:810:18
at IncomingMessage.<anonymous> (/Users/cchang/projects/adobesign-widget-manager/node_modules/superagent/lib/node/parsers/json.js:16:7)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:934:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by timsmith339** [comment]
I'm guessing there hasn't been any updates on this?  I forked and fixed it, but I fear it may be causing other side effects.
