### ISSUE TITLE
Error: Cannot find module 'adobe-sign-sdk'

### ISSUE THREAD

**Issue by sichen** [adobe-sign/AdobeSignJsSdk#5]
When I follow Readme and try to run a test, I got the error:

$ node_modules/grunt/bin/grunt Sample:CreateNewUserInAccount

Running "Sample:CreateNewUserInAccount" (Sample) task

Running "run:CreateNewUserInAccount" (run) task
module.js:471
    throw err;
    ^

Error: Cannot find module 'adobe-sign-sdk'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at UserUtils (/Users/sichen/temp/AdobeSignJsSdk/rest-api-sample/utils/UserUtils.js:17:30)
    at Object.<anonymous> (/Users/sichen/temp/AdobeSignJsSdk/rest-api-sample/utils/UserUtils.js:19:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
Warning: non-zero exit code 1 Use --force to continue.

I tried to install "adobe-sign-sdk" but failed because "Refusing to install adobe-sign-sdk as a dependency of itself"

What's the exact steps to run the samples?

**Comment by matthewsanders** [comment]
In a pinch you should be able to search for all of the require('adobe-sign-sdk') usage and replace with: require('../../')

**Comment by wind13** [comment]
+1
